name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona el entorno de despliegue'
        required: true
        type: choice
        options:
          - dev
          - test
          - pre
          - pro

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en el entorno seleccionado
        run: echo "Desplegando en el entorno ${{ github.event.inputs.environment }}"

    # Configuración de aprobación manual para entornos `pre` y `pro`
    environment:
      name: ${{ github.event.inputs.environment }}
      url: https://your-application-url.com
      # Solo solicita aprobación para `pre` y `pro`
      if: ${{ github.event.inputs.environment == 'pre' || github.event.inputs.environment == 'pro' }}
      reviewers:
        - DevOps  # Cambia esto al nombre del equipo que configuraste
